[package]
name = "cppsafe"
version = "0.1.0"
std = 20

[dependencies]
llvm = { version="17.0.2", components=["clangTooling"], options={ with_project_clang=true, conan_center_index_limits=false} }
ms-gsl = "4.0.0"
fmt = "10.1.1"
range-v3 = "0.12.0"
nextsilicon-cpp-subprocess = "2.0.2"

[target.'cfg(not(compiler = "msvc"))'.profile]
cxxflags = ["-Wall", "-Wextra", "-Werror", "-Wno-unused-parameter", "-Wno-missing-field-initializers"]

[target.'cfg(not(compiler = "msvc"))'.profile.debug]
ubsan = true

# macos with gcc11 has bugs in asan:
# `member call on address 0x60b0000001a0 which does not point to an object of type '_Sp_counted_base'`
[target.'cfg(any(os = "linux", compiler = "clang", compiler = "apple_clang"))'.profile.debug]
asan = true